language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y python2.7 python-gi python3-gi python3-gi-cairo python-gobject gir1.2-gtk-3.0 python-gi-cairo python-mpltoolkits.basemap python-numpy python-matplotlib python-libhamlib2

install:
  - sudo make install

before_script:
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - "export DISPLAY=:99.0"
  
script:
  - make unittest
  - sudo make clean

